'use strict';

/**
 * Curated schema.org vocabulary subset.
 *
 * Covers types and properties relevant to medical/aesthetic practice websites.
 * Kept in sync with https://schema.org/version/latest/schemaorg-current-https.jsonld
 *
 * Format mirrors the output of schema-validator.js buildIndex():
 *   types:      Set<string>
 *   propDomains: Map<propName, Set<domainTypeNames>>  (empty Set = valid on all)
 *   parents:    Map<typeName, Set<parentTypeNames>>
 */

// ─── Type hierarchy ────────────────────────────────────────────────────────────
// Each entry: typeName → [parentTypeNames]

const TYPE_PARENTS = {
  Thing: [],
  Action: ['Thing'],
  Intangible: ['Thing'],
  CreativeWork: ['Thing'],
  Event: ['Thing'],
  MedicalEntity: ['Thing'],
  MedicalIntangible: ['MedicalEntity'],
  Place: ['Thing'],
  Organization: ['Thing'],
  Person: ['Thing'],
  Product: ['Thing'],
  Enumeration: ['Intangible'],
  Rating: ['Intangible'],
  StructuredValue: ['Intangible'],
  ItemList: ['Intangible'],
  Offer: ['Intangible'],
  Brand: ['Intangible'],
  Language: ['Intangible'],
  Audience: ['Intangible'],
  AlignmentObject: ['Intangible'],
  ServiceChannel: ['Intangible'],
  Role: ['Intangible'],
  SpeakableSpecification: ['Intangible'],
  EntryPoint: ['Intangible'],
  BreadcrumbList: ['ItemList'],
  HowToStep: ['ItemList', 'CreativeWork'],
  OfferCatalog: ['ItemList'],
  ListItem: ['Intangible'],
  PriceSpecification: ['StructuredValue'],
  MonetaryAmount: ['StructuredValue'],
  QuantitativeValue: ['StructuredValue'],
  PropertyValue: ['StructuredValue'],
  GeoCoordinates: ['StructuredValue'],
  GeoShape: ['StructuredValue'],
  ContactPoint: ['StructuredValue'],
  OpeningHoursSpecification: ['StructuredValue'],
  PostalAddress: ['ContactPoint'],
  AggregateRating: ['Rating'],
  AggregateOffer: ['Offer'],
  MediaObject: ['CreativeWork'],
  ImageObject: ['MediaObject'],
  VideoObject: ['MediaObject'],
  AudioObject: ['MediaObject'],
  WebSite: ['CreativeWork'],
  WebPage: ['CreativeWork'],
  WebPageElement: ['CreativeWork'],
  Article: ['CreativeWork'],
  BlogPosting: ['SocialMediaPosting'],
  SocialMediaPosting: ['Article'],
  NewsArticle: ['Article'],
  TechArticle: ['Article'],
  MedicalWebPage: ['WebPage'],
  FAQPage: ['WebPage'],
  QAPage: ['WebPage'],
  AboutPage: ['WebPage'],
  ContactPage: ['WebPage'],
  CollectionPage: ['WebPage'],
  ProfilePage: ['WebPage'],
  CheckoutPage: ['WebPage'],
  Question: ['Comment'],
  Answer: ['Comment'],
  Comment: ['CreativeWork'],
  Review: ['CreativeWork'],
  CriticReview: ['Review'],
  PublicationEvent: ['Event'],
  MedicalEvent: ['Event', 'MedicalEntity'],
  LocalBusiness: ['Organization', 'Place'],
  MedicalOrganization: ['LocalBusiness'],
  MedicalClinic: ['MedicalOrganization'],
  Physician: ['MedicalOrganization'],
  MedSpa: ['LocalBusiness'],
  Dentist: ['LocalBusiness', 'MedicalOrganization'],
  Dermatologist: ['MedicalOrganization'],
  Optician: ['MedicalOrganization'],
  HospitalDepartment: ['MedicalOrganization'],
  Hospital: ['MedicalOrganization'],
  DiagnosticLab: ['MedicalOrganization'],
  GovernmentOrganization: ['Organization'],
  Corporation: ['Organization'],
  EducationalOrganization: ['Organization'],
  SportsOrganization: ['Organization'],
  ProfessionalService: ['LocalBusiness'],
  FinancialService: ['LocalBusiness'],
  BeautySalon: ['HealthAndBeautyBusiness'],
  DaySpa: ['HealthAndBeautyBusiness'],
  HealthAndBeautyBusiness: ['LocalBusiness'],
  HealthClub: ['HealthAndBeautyBusiness'],
  NailSalon: ['HealthAndBeautyBusiness'],
  TattooParlor: ['HealthAndBeautyBusiness'],
  Pharmacy: ['MedicalOrganization', 'Store'],
  Store: ['LocalBusiness'],
  FoodEstablishment: ['LocalBusiness'],
  Restaurant: ['FoodEstablishment'],
  Service: ['Intangible'],
  MedicalProcedure: ['MedicalEntity'],
  MedicalTherapy: ['MedicalProcedure'],
  PhysicalTherapy: ['MedicalTherapy'],
  SurgicalProcedure: ['MedicalProcedure'],
  PalliativeProcedure: ['MedicalProcedure'],
  MedicalCondition: ['MedicalEntity'],
  MedicalTrial: ['MedicalStudy'],
  MedicalStudy: ['MedicalEntity'],
  Drug: ['Substance'],
  Substance: ['MedicalEntity'],
  DietarySupplement: ['Substance'],
  MedicalGuideline: ['MedicalEntity'],
  MedicalRiskFactor: ['MedicalEntity'],
  MedicalSign: ['MedicalEntity'],
  MedicalSymptom: ['MedicalSign'],
  MedicalSpecialty: ['MedicalEnumeration', 'Specialty'],
  MedicalEnumeration: ['Enumeration'],
  Specialty: ['Enumeration'],
  AnatomicalStructure: ['MedicalEntity'],
  AnatomicalSystem: ['MedicalEntity'],
  SuperficialAnatomy: ['MedicalEntity'],
  Country: ['Place'],
  AdministrativeArea: ['Place'],
  Accommodation: ['Place'],
  LandmarksOrHistoricalBuildings: ['Place'],
  GatedResidenceCommunity: ['Residence'],
  Residence: ['Place'],
  Apartment: ['Accommodation'],
  CivicStructure: ['Place'],
  BookStore: ['Store'],
};

// ─── Properties ────────────────────────────────────────────────────────────────
// Each entry: propName → [domainTypeNames]
// Empty array means "valid on any type" (schema:Thing or no restriction).
// For medical use-cases we list representative domains; validator uses these
// for warnings (not errors) since schema.org domainIncludes is non-restrictive.

const PROP_DOMAINS = {
  // Thing — universally applicable
  name: ['Thing'],
  description: ['Thing'],
  url: ['Thing'],
  image: ['Thing'],
  sameAs: ['Thing'],
  identifier: ['Thing'],
  additionalType: ['Thing'],
  alternateName: ['Thing'],
  disambiguatingDescription: ['Thing'],
  mainEntityOfPage: ['Thing'],
  potentialAction: ['Thing'],
  subjectOf: ['Thing'],

  // CreativeWork
  about: ['CreativeWork'],
  abstract: ['CreativeWork'],
  accessMode: ['CreativeWork'],
  accountablePerson: ['CreativeWork'],
  author: ['CreativeWork'],
  award: ['CreativeWork'],
  character: ['CreativeWork'],
  citation: ['CreativeWork'],
  comment: ['CreativeWork'],
  contentLocation: ['CreativeWork'],
  contentRating: ['CreativeWork'],
  contributor: ['CreativeWork'],
  copyrightHolder: ['CreativeWork'],
  copyrightYear: ['CreativeWork'],
  creator: ['CreativeWork'],
  dateCreated: ['CreativeWork'],
  dateModified: ['CreativeWork'],
  datePublished: ['CreativeWork'],
  editor: ['CreativeWork'],
  encoding: ['CreativeWork'],
  encodingFormat: ['CreativeWork'],
  exampleOfWork: ['CreativeWork'],
  funder: ['CreativeWork'],
  genre: ['CreativeWork'],
  hasPart: ['CreativeWork'],
  headline: ['CreativeWork'],
  inLanguage: ['CreativeWork'],
  interactionStatistic: ['CreativeWork'],
  isAccessibleForFree: ['CreativeWork'],
  isBasedOn: ['CreativeWork'],
  isFamilyFriendly: ['CreativeWork'],
  isPartOf: ['CreativeWork'],
  keywords: ['CreativeWork'],
  license: ['CreativeWork'],
  material: ['CreativeWork', 'Product'],
  mentions: ['CreativeWork'],
  position: ['CreativeWork', 'ListItem'],
  producer: ['CreativeWork'],
  provider: ['CreativeWork', 'Service'],
  publication: ['CreativeWork'],
  publisher: ['CreativeWork'],
  publishingPrinciples: ['CreativeWork'],
  review: ['CreativeWork', 'Product', 'LocalBusiness', 'Service'],
  schemaVersion: ['CreativeWork'],
  sdPublisher: ['CreativeWork'],
  sourceOrganization: ['CreativeWork'],
  spatial: ['CreativeWork'],
  sponsor: ['CreativeWork', 'Event', 'Person', 'Organization'],
  teaches: ['CreativeWork'],
  temporal: ['CreativeWork'],
  text: ['CreativeWork'],
  thumbnailUrl: ['CreativeWork'],
  timeRequired: ['CreativeWork'],
  translator: ['CreativeWork'],
  typicalAgeRange: ['CreativeWork'],
  version: ['CreativeWork'],
  video: ['CreativeWork'],
  wordCount: ['Article'],

  // Article / BlogPosting
  articleBody: ['Article'],
  articleSection: ['Article'],
  backstory: ['ReportageNewsArticle'],
  pageEnd: ['Article'],
  pageStart: ['Article'],
  pagination: ['Article'],

  // WebSite
  // (inherits CreativeWork props + adds:)

  // WebPage
  breadcrumb: ['WebPage'],
  lastReviewed: ['WebPage'],
  mainContentOfPage: ['WebPage'],
  primaryImageOfPage: ['WebPage'],
  relatedLink: ['WebPage'],
  reviewedBy: ['WebPage'],
  significantLink: ['WebPage'],
  speakable: ['WebPage'],

  // WebPage — mainEntity is the "main thing" described by the page
  mainEntity: ['WebPage'],

  // FAQ / Q&A
  answerCount: ['Question'],
  acceptedAnswer: ['Question'],
  suggestedAnswer: ['Question'],
  downvoteCount: ['Question', 'Answer'],
  upvoteCount: ['Question', 'Answer'],
  parentItem: ['Comment'],

  // Organization / LocalBusiness
  address: ['Organization', 'Person', 'Place'],
  aggregateRating: ['Organization', 'Product', 'Service', 'CreativeWork'],
  areaServed: ['Organization', 'ContactPoint', 'Service', 'Offer'],
  branchCode: ['LocalBusiness'],
  branchOf: ['LocalBusiness'],
  contactPoint: ['Organization', 'Person'],
  currenciesAccepted: ['LocalBusiness'],
  department: ['Organization'],
  dissolutionDate: ['Organization'],
  duns: ['Organization'],
  email: ['Organization', 'ContactPoint', 'Person'],
  employee: ['Organization'],
  faxNumber: ['Organization', 'ContactPoint', 'Person', 'Place'],
  founder: ['Organization'],
  foundingDate: ['Organization'],
  foundingLocation: ['Organization'],
  globalLocationNumber: ['Organization', 'Place'],
  hasCredential: ['Person', 'Organization'],
  hasOfferCatalog: ['Organization', 'Service', 'Person'],
  hasPOS: ['Organization'],
  isicV4: ['Organization', 'Person', 'Place'],
  knowsAbout: ['Organization', 'Person'],
  knowsLanguage: ['Organization', 'Person'],
  legalName: ['Organization'],
  leiCode: ['Organization'],
  location: ['Event', 'Organization', 'Action'],
  logo: ['Organization', 'Place', 'Product', 'Service'],
  makesOffer: ['Organization', 'Person'],
  member: ['Organization'],
  memberOf: ['Organization', 'Person'],
  naics: ['Organization', 'Person'],
  numberOfEmployees: ['Organization'],
  parentOrganization: ['Organization'],
  paymentAccepted: ['LocalBusiness'],
  photo: ['LocalBusiness', 'Person', 'Place'],
  priceRange: ['LocalBusiness'],
  serviceArea: ['Organization', 'ContactPoint'],
  slogan: ['Organization', 'Product', 'Service'],
  subOrganization: ['Organization'],
  taxID: ['Organization'],
  telephone: ['Organization', 'ContactPoint', 'Person', 'Place'],
  vatID: ['Organization'],

  // MedicalOrganization specifics
  healthPlanNetworkId: ['MedicalOrganization'],
  isAcceptingNewPatients: ['MedicalOrganization'],
  medicalSpecialty: ['MedicalOrganization', 'Physician', 'Hospital'],

  // Place
  additionalProperty: ['Place', 'Product'],
  amenityFeature: ['Place', 'Accommodation', 'LodgingBusiness'],
  containedInPlace: ['Place'],
  containsPlace: ['Place'],
  geo: ['Place'],
  geoContains: ['Place'],
  geoCoveredBy: ['Place'],
  geoCovers: ['Place'],
  geoCrosses: ['Place'],
  geoDisjoint: ['Place'],
  geoEquals: ['Place'],
  geoIntersects: ['Place'],
  geoOverlaps: ['Place'],
  geoTouches: ['Place'],
  geoWithin: ['Place'],
  hasMap: ['Place'],
  isicV4: ['Place'],
  latitude: ['Place', 'GeoCoordinates'],
  longitude: ['Place', 'GeoCoordinates'],
  map: ['Place'],
  maximumAttendeeCapacity: ['Place'],
  openingHours: ['LocalBusiness', 'CivicStructure'],
  openingHoursSpecification: ['Place'],
  publicAccess: ['Place'],
  smokingAllowed: ['Place', 'Accommodation'],
  specialOpeningHoursSpecification: ['Place'],
  tourBookingPage: ['Place'],

  // GeoCoordinates
  elevation: ['GeoCoordinates', 'GeoShape'],
  addressCountry: ['GeoCoordinates', 'GeoShape', 'PostalAddress'],

  // OpeningHoursSpecification
  closes: ['OpeningHoursSpecification'],
  dayOfWeek: ['OpeningHoursSpecification'],
  opens: ['OpeningHoursSpecification'],
  validFrom: ['OpeningHoursSpecification', 'Offer', 'PriceSpecification'],
  validThrough: ['OpeningHoursSpecification', 'Offer', 'PriceSpecification'],

  // ContactPoint / PostalAddress
  availableLanguage: ['ContactPoint', 'LodgingBusiness'],
  contactOption: ['ContactPoint'],
  contactType: ['ContactPoint'],
  hoursAvailable: ['ContactPoint', 'LocationFeatureSpecification'],
  productSupported: ['ContactPoint'],
  servicePostalAddress: ['ServiceChannel'],
  addressLocality: ['PostalAddress'],
  addressRegion: ['PostalAddress'],
  postOfficeBoxNumber: ['PostalAddress'],
  postalCode: ['PostalAddress'],
  streetAddress: ['PostalAddress'],

  // Person
  affiliation: ['Person'],
  alumniOf: ['Person'],
  awards: ['Person', 'Product', 'CreativeWork'],
  birthDate: ['Person'],
  birthPlace: ['Person'],
  brand: ['Organization', 'Person', 'Product', 'Service'],
  children: ['Person'],
  colleague: ['Person'],
  deathDate: ['Person'],
  deathPlace: ['Person'],
  familyName: ['Person'],
  follows: ['Person'],
  gender: ['Person'],
  givenName: ['Person'],
  hasOccupation: ['Person'],
  height: ['Person', 'MediaObject', 'Product'],
  homeLocation: ['Person'],
  honorificPrefix: ['Person'],
  honorificSuffix: ['Person'],
  interactionStatistic: ['CreativeWork', 'Person'],
  jobTitle: ['Person'],
  knows: ['Person'],
  makesOffer: ['Person'],
  nationality: ['Person'],
  netWorth: ['Person'],
  owns: ['Person', 'Organization'],
  parent: ['Person'],
  performerIn: ['Person'],
  publishingPrinciples: ['Person', 'Organization'],
  relatedTo: ['Person'],
  seeks: ['Person'],
  sibling: ['Person'],
  spouse: ['Person'],
  taxID: ['Person'],
  vatID: ['Person'],
  weight: ['Person', 'Product'],
  workLocation: ['Person'],
  worksFor: ['Person'],

  // Service
  availableChannel: ['Service'],
  category: ['Service', 'Product', 'Offer'],
  hasOfferCatalog: ['Service'],
  offers: ['Service', 'Product', 'Event'],
  serviceArea: ['Service'],
  serviceAudience: ['Service'],
  serviceOutput: ['Service'],
  serviceType: ['Service'],
  termsOfService: ['Service'],

  // MedicalProcedure / MedicalTherapy
  bodyLocation: ['MedicalProcedure'],
  followup: ['MedicalProcedure'],
  howPerformed: ['MedicalProcedure'],
  indication: ['MedicalProcedure', 'MedicalDevice'],
  preparation: ['MedicalProcedure'],
  procedureType: ['MedicalProcedure'],
  recognizingAuthority: ['MedicalEntity'],
  relevantSpecialty: ['MedicalEntity'],
  status: ['MedicalEntity', 'MedicalStudy'],
  study: ['MedicalEntity'],

  // Rating / AggregateRating
  ratingCount: ['AggregateRating'],
  ratingExplanation: ['Rating'],
  ratingValue: ['Rating'],
  bestRating: ['Rating'],
  worstRating: ['Rating'],
  reviewCount: ['AggregateRating'],
  reviewAspect: ['Review', 'Guide'],
  reviewBody: ['Review'],
  reviewRating: ['Review'],
  itemReviewed: ['Review', 'Rating'],
  associatedReview: ['AggregateRating'],

  // Offer
  acceptedPaymentMethod: ['Offer', 'LoanOrCredit'],
  addOn: ['Offer'],
  advanceBookingRequirement: ['Offer', 'Demand'],
  availability: ['Offer', 'Demand'],
  availabilityEnds: ['Offer', 'Demand'],
  availabilityStarts: ['Offer', 'Demand'],
  availableAtOrFrom: ['Offer', 'Demand'],
  availableDeliveryMethod: ['Offer', 'Demand'],
  businessFunction: ['Offer', 'Demand'],
  deliveryLeadTime: ['Offer', 'Demand'],
  eligibleCustomerType: ['Offer', 'Demand'],
  eligibleDuration: ['Offer', 'Demand'],
  eligibleQuantity: ['Offer', 'Demand'],
  eligibleRegion: ['Offer', 'Demand', 'ActionAccessSpecification'],
  gtin: ['Offer', 'Product'],
  gtin12: ['Offer', 'Product'],
  gtin13: ['Offer', 'Product'],
  gtin14: ['Offer', 'Product'],
  gtin8: ['Offer', 'Product'],
  includesObject: ['Offer'],
  inventoryLevel: ['Offer', 'SomeProducts'],
  itemCondition: ['Offer', 'Product'],
  itemOffered: ['Offer'],
  leaseLength: ['Offer', 'Accommodation'],
  mpn: ['Offer', 'Product'],
  offeredBy: ['Offer'],
  price: ['Offer', 'TradeAction', 'PriceSpecification'],
  priceCurrency: ['Offer', 'Reservation', 'PriceSpecification'],
  priceSpecification: ['Offer', 'TradeAction'],
  priceValidUntil: ['Offer'],
  seller: ['Offer'],
  serialNumber: ['Offer', 'IndividualProduct'],
  sku: ['Offer', 'Product'],
  warranty: ['Offer', 'Product'],

  // Product
  color: ['Product'],
  depth: ['Product'],
  gtin: ['Product'],
  hasMerchantReturnPolicy: ['Product'],
  isConsumableFor: ['Product'],
  isSimilarTo: ['Product', 'Service'],
  isVariantOf: ['Product'],
  manufacturer: ['Product'],
  model: ['Product', 'Organization'],
  productID: ['Product'],
  productionDate: ['Product'],
  purchaseDate: ['Product'],
  releaseDate: ['Product'],
  slogan: ['Product'],
  weight: ['Product'],
  width: ['Product'],

  // MediaObject / ImageObject / VideoObject
  associatedArticle: ['MediaObject'],
  bitrate: ['MediaObject'],
  contentSize: ['MediaObject'],
  contentUrl: ['MediaObject'],
  duration: ['MediaObject', 'Movie', 'MusicRecording', 'Audiobook'],
  embedUrl: ['MediaObject'],
  endTime: ['MediaObject', 'Clip'],
  playerType: ['MediaObject'],
  productionCompany: ['MediaObject'],
  requiresSubscription: ['MediaObject'],
  startTime: ['MediaObject', 'Clip'],
  uploadDate: ['MediaObject'],
  caption: ['ImageObject', 'VideoObject'],
  exifData: ['ImageObject'],
  representativeOfPage: ['ImageObject'],
  thumbnail: ['ImageObject', 'VideoObject'],
  videoFrameSize: ['VideoObject'],
  videoQuality: ['VideoObject'],
  actor: ['VideoObject'],
  director: ['VideoObject'],
  musicBy: ['VideoObject'],
  subtitleLanguage: ['VideoObject'],
  transcript: ['VideoObject'],

  // Event
  about: ['Event'],
  attendee: ['Event'],
  attendees: ['Event'],
  composer: ['Event', 'MusicComposition'],
  doorTime: ['Event'],
  endDate: ['Event', 'CreativeWork', 'Role'],
  eventAttendanceMode: ['Event'],
  eventSchedule: ['Event'],
  eventStatus: ['Event'],
  inLanguage: ['Event'],
  isAccessibleForFree: ['Event'],
  maximumAttendeeCapacity: ['Event'],
  maximumPhysicalAttendeeCapacity: ['Event'],
  maximumVirtualAttendeeCapacity: ['Event'],
  offers: ['Event'],
  organizer: ['Event'],
  performer: ['Event'],
  previousStartDate: ['Event'],
  recordedIn: ['Event'],
  remainingAttendeeCapacity: ['Event'],
  review: ['Event'],
  startDate: ['Event', 'CreativeWork', 'Role'],
  subEvent: ['Event'],
  superEvent: ['Event'],
  typicalAgeRange: ['Event'],
  workFeatured: ['Event'],
  workPerformed: ['Event'],

  // BreadcrumbList / ListItem
  itemListElement: ['ItemList'],
  itemListOrder: ['ItemList'],
  numberOfItems: ['ItemList'],
  item: ['ListItem'],
  nextItem: ['ListItem'],
  previousItem: ['ListItem'],

  // PriceSpecification / MonetaryAmount
  maxPrice: ['PriceSpecification'],
  minPrice: ['PriceSpecification'],
  valueAddedTaxIncluded: ['PriceSpecification'],
  currency: ['MonetaryAmount'],
  maxValue: ['MonetaryAmount', 'QuantitativeValue', 'PropertyValue'],
  minValue: ['MonetaryAmount', 'QuantitativeValue', 'PropertyValue'],
  value: ['MonetaryAmount', 'QuantitativeValue', 'PropertyValue'],
  unitCode: ['QuantitativeValue', 'PropertyValue'],
  unitText: ['QuantitativeValue', 'PropertyValue'],

  // PropertyValue
  maxValue: ['PropertyValue'],
  minValue: ['PropertyValue'],
  propertyID: ['PropertyValue'],
  value: ['PropertyValue'],
  valueReference: ['PropertyValue'],
};

// ─── Export in the same shape as buildIndex() ──────────────────────────────────

function buildCuratedIndex() {
  const types = new Set(Object.keys(TYPE_PARENTS));
  const propDomains = new Map(Object.entries(PROP_DOMAINS).map(([k, v]) => [k, new Set(v)]));
  const parents = new Map(Object.entries(TYPE_PARENTS).map(([k, v]) => [k, new Set(v)]));
  return { types, propDomains, parents };
}

module.exports = buildCuratedIndex();
